
sudo: false

language: python

install: pip install codecov tox

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=pypy3
  - TOX_ENV=coverage
  - TOX_ENV=pep8

script:
  - tox -e $TOX_ENV
