version: '2'

services:
  pystock:
    image: pystock
    build:
      context: ./
    container_name: pystock
    env_file: .env
    volumes:
        - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    entrypoint: sh -c "python setup.py develop && bash"

  tornado:
    extends: pystock
    container_name: tornado
    ports:
      - 10002:8080
    entrypoint: sh -c "python setup.py develop && bash"

  jupyter:
    extends: pystock
    container_name: pystock-jupyter
    ports:
      - 10003:80
    entrypoint: sh -c "python setup.py develop && ./start_jupyter --allow-root"
