version: '2'

services:
  pystock:
    image: pystock
    build:
      context: ./
    container_name: pystock
    env_file: .env
    volumes:
        - .:/app
    working_dir: /app
    ports:
      - 8080
    tty: true
    stdin_open: true
    entrypoint: sh -c "python setup.py develop && bash"
