# サーバーをデーモンで起動(まとめて)
# docker-compose up -d
# ここに起動
# docker-compose run base repo mysql server

version: '2'

# docker build -t pystock-base -f ./base/Dockerfile .
services:
  base:
    build: ./base
    container_name: pystock_base

  pystock_repo:
    image: centos
    container_name: pystock_repo
    volumes:
        - ../:/pystock

  # 以下のコマンドで起動中のmysqlのコンソールに入れる
  # docker exec -it docker_mysql_1 mysql stock
  # snapshot
  # docker commit docker_mysql_1 docker_mysql_1:v1
  # 別名の方がよい?
  # docker commit docker_mysql_1 OTHER
  mysql:
    image: mysql
    ports:
        - "3306:3306"
    volumes:
        - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_DATABASE: stock

  # 開発中は、以下のコマンドを実行しておく(ENVは設定されてるけど、portは違うみたいとかなんかある)
  # docker-compose run web
  web:
    image: docker_base
    # build: ./web
    ports:
        - "8002:80"
    volumes_from:
        - pystock_repo
    environment:
        DATABASE_URL: "mysql+pymysql://root@192.168.99.100:3306/stock?charset=utf8"
    depends_on:
        - base
        - pystock_repo
    working_dir: /pystock

    # docker start NAME && docker attach NAME
    stdin_open: true
    tty: true

    # entrypointがあるとattachできないみたい
    # I don't know how to use???
    # entrypoint: python3 setup.py develop

    # mysqlが完全に立ち上がるのを待つ必要がある。(composeでは、待ちを判断できない.)
    # command: pystock setup
    # command: sh -c "/bin/pip3 install -r /pystock/requirements.txt && /bin/python3.4 /pystock/setup.py develop"

    # web can't wait for mysql to start completely. so manually run this
    # pystock setup && pystock serve --port 80 --host 0.0.0.0
