version: '2'

volumes:
  pystock_volume:
    driver: local

services:
  mysql:
    image: mysql:5.7
    volumes:
        - ./mysql/conf.d:/etc/mysql/conf.d
        - pystock_volume:/var/lib/mysql
        - ..:/docker
    working_dir: /docker
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_DATABASE: db

  # this should be always working on local for checking
  test:
    build:
      context: ../
      dockerfile: ./docker/base/Dockerfile
    ports:
      - 80
    environment:
      DATABASE_URL: "mysql+pymysql://root@db:3306/stock?charset=utf8"

    links:
      - mysql:db
    volumes:
        - ..:/repo
    depends_on:
        - mysql
    working_dir: /repo

    # ttyを設定しない場合は直接入るみたい(ttyの設定は必須)
    stdin_open: true
    # command: gunicorn -b 0.0.0.0:80 stock.server.main:app --log-file -
    entrypoint: sh -c "python setup.py develop && pystock setup && pystock serve --port 80 --host 0.0.0.0"

  web:
    build:
      context: ../
      dockerfile: ./docker/base/Dockerfile
    ports:
      - 80
    environment:
        DATABASE_URL: "mysql+pymysql://root@db:3306/stock?charset=utf8"
    links:
      - mysql:db
    volumes:
        - ..:/repo
    depends_on:
        - mysql
    working_dir: /repo

    # ttyを設定しない場合は直接入るみたい(ttyの設定は必須)
    tty: true
    stdin_open: true
