version: '2'

volumes:
  pystock_volume:
    driver: local

services:
  base:
    build:
      context: ../
      dockerfile: ./docker/base/Dockerfile

  pystock_repo:
    image: centos
    volumes:
        - ../:/pystock

  mysql:
    image: mysql:5.7
    volumes:
        - ./mysql/conf.d:/etc/mysql/conf.d
        - pystock_volume:/var/lib/mysql
        - ..:/docker
    working_dir: /docker
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_DATABASE: stock

  # this should be always working on local for checking
  test:
    build: ./test
    depends_on:
        - mysql
    links:
      - mysql:db
    ports:
        - "9002:80"
    environment:
        DATABASE_URL: "mysql+pymysql://root@db:3306/stock?charset=utf8"

    # command: gunicorn -b 0.0.0.0:80 stock.server.main:app --log-file -
    entrypoint: pystock serve --port 80 --host 0.0.0.0

  web:
    image: docker_base
    container_name: pystock_web
    ports:
        - "8002:80"
    volumes_from:
        - pystock_repo
    environment:
        DATABASE_URL: "mysql+pymysql://root@db:3306/stock?charset=utf8"
    links:
      - mysql:db
    depends_on:
        - base
        - mysql
        - pystock_repo
    working_dir: /pystock

    # ttyを設定しない場合は直接入るみたい(ttyの設定は必須)
    # docker-compose run web
    tty: true
    stdin_open: true
