---

- hosts: server
  remote_user: root  # TODO: ubuntu
  gather_facts: no
  tasks:
  - git:
      repo: git@github.com:her0e1c1/pystock.git
      dest: ~/pystock
      update: yes
      force: yes
      accept_hostkey: True

  - cron:
      cron_file: pystock
      user: root
      hour: 16  # at 12 in jp 
      name: import-all-codes
      job: "docker exec pystock pystock quandl import-all-codes -f TSE 2>&1 | logger -t pystock -p local0.info"

  - cron:
      cron_file: pystock
      user: root
      hour: 0  # at 12 in jp 
      name: predict-buying-prices
      job: "docker exec pystock pystock predict2 2>&1 | logger -t pystock -p local0.info"

  - cron:
      cron_file: pystock
      user: root
      hour: "18"
      name: predict
      job: "docker exec pystock pystock predict 2>&1 | logger -t pystock -p local0.info"

  - cron:
      cron_file: pystock
      user: root
      hour: "19"
      name: predict-rsi
      job: "docker exec pystock pystock predict -s rsi 2>&1 | logger -t pystock -p local0.info"

  - cron:
      cron_file: pystock
      user: root
      hour: "20"
      name: predict-macd
      job: "docker exec pystock pystock predict -s macd_signal 2>&1 | logger -t pystock -p local0.info"

  - copy:
      src: ../.env
      dest: ~/pystock
      mode: 0644

  - docker_image:
      path: ~/pystock
      name: pystock

  - docker_service:
      files:
        - docker-compose.yml
        - docker-compose.prod.yml
      project_src: ~/pystock
      build: yes
      restarted: yes
